### ISSUE TITLE
代码块看不清

### ISSUE THREAD

**Issue by YH2021-cc** [obscurefreeman/typora_theme_blackout#1]
该主题下代码块根本看不清
![image](https://github.com/obscurefreeman/typora_theme_blackout/assets/84270940/5d5a9814-cbb4-42b2-9374-96ad411739d0)

**Comment by YH2021-cc** [comment]
@obscurefreeman 能否优化下,谢谢

**Comment by obscurefreeman** [comment]
用的是苹果系统吗？有没有将obscurefreeman这个文件夹放进去。

**Comment by obscurefreeman** [comment]
是这样的，你没有将obscurefreeman文件夹一起放到主题文件夹里。

**Comment by YH2021-cc** [comment]
解决了确实是没放到主题文件夹里
