### ISSUE TITLE
导入按钮文字看不清

### ISSUE THREAD

**Issue by shanyan-wcx** [obscurefreeman/typora_theme_blackout#11]
![image](https://github.com/obscurefreeman/typora_theme_blackout/assets/58252651/13173731-431a-40cf-93a0-c87d8c2b736e)

**Comment by obscurefreeman** [comment]
收到

**Comment by obscurefreeman** [comment]
已在最新的更新中修复，鼠标悬停时文字会呈现黑色，若感觉有违和感我还会继续修改。
