### ISSUE TITLE
字体太亮了

### ISSUE THREAD

**Issue by wovvvv** [obscurefreeman/typora_theme_blackout#16]
要是可以把字体亮度降低一点就好，像github 黑暗模式一样

**Comment by wovvvv** [comment]
每次点进去typora都感觉刺眼，主题明明是暗色模式，字体没必要这么亮，很刺眼

**Comment by obscurefreeman** [comment]
了解了。如果你觉得字体亮度不适合你，可以在这里修改文字的颜色。
比如你想让`blackout`主题的字体不那么亮，你可以去插件文件夹`C:\Users\Lenovo\AppData\Roaming\Typora\themes`找到`blackout.css`并修改下面的代码。

![image](https://github.com/user-attachments/assets/603f9baf-2183-441a-899c-d32656f10153)

**Comment by zhouxinghong** [comment]
字体亮度刚刚好。。。请保持默认亮度。
