### ISSUE TITLE
代码高亮有点抽象

### ISSUE THREAD

**Issue by yangyibufeng** [obscurefreeman/typora_theme_blackout#17]
![image](https://github.com/user-attachments/assets/54d902bb-84bb-43e2-a589-45d61a86caf1)
Java代码的高亮结合深色背景来看有点抽象，大佬可以考虑改进一下，我是直接把代码类型给删了纯白的看着也还凑合

**Comment by obscurefreeman** [comment]
![Snipaste_2024-08-02_19-03-30](https://github.com/user-attachments/assets/eeb8fda4-6f85-431c-be2c-18e9ee17301c)
安装主题时是不是忘记把文件夹拖进去了？
