### ISSUE TITLE
搜索的高亮颜色修改

### ISSUE THREAD

**Issue by JeffYoung00** [obscurefreeman/typora_theme_blackout#18]
typora默认搜索是黑色高亮，我用切尔诺贝利蓝看着就很难受，问一下哪里可以改吗？
![image](https://github.com/user-attachments/assets/2fcc0464-7fd9-43c8-8731-d2580b327719)

**Comment by obscurefreeman** [comment]
已解决，新版本发布：https://github.com/obscurefreeman/typora_theme_blackout/releases/tag/V1.0.8
已将搜索高亮颜色从暗色改成主题强调色，如果觉得主题色不明显，请在`css`文件中找到`--search-select-bg-color`修改成你想要的颜色。
