### ISSUE TITLE
There is a problem with the code language display.

### ISSUE THREAD

**Issue by zhouxinghong** [obscurefreeman/typora_theme_blackout#19]
There is a problem with the code language display.
Wrong:
![image](https://github.com/user-attachments/assets/a860ef33-3fe9-4db3-add1-ddbffd74d003)
Normal:
![image](https://github.com/user-attachments/assets/335d8559-15eb-406a-92e6-012a3a859035)

**Comment by obscurefreeman** [comment]
ok, I'll take a look

**Comment by zhouxinghong** [comment]
The default theme does not have this problem.
