### ISSUE TITLE
脚注留白和快速打开文件的显示问题

### ISSUE THREAD

**Issue by rchqi** [obscurefreeman/typora_theme_blackout#21]
你好大大
1.脚注留白
代码：
sadsahksa[^1]
[^1]:sdsdfdf

导出的html效果:
图一为大大的gamer，未留白；图二为自带的github主题，导出html自动留白
请问可以修改哪处的代码进行留白设置。
![Snipaste_2024-10-26_23-24-52](https://github.com/user-attachments/assets/27c143b0-6b23-4833-82b5-1ae1c4b21fd2)
![Snipaste_2024-10-26_23-24-49](https://github.com/user-attachments/assets/fc5a8886-03b7-45c9-a647-3a0ecd99ff6f)

2.快速打开文件显示
默认高亮第一个文件，但是鼠标在其余的文件名上的时候，高亮不变，还是在第一个文件，鼠标所在的文件名的字体也没有变为加粗效果(大大的橙色的那款主题有这种效果)
请问这个就是这样设计的，还是css文件被其他的css文件干扰了
![Snipaste_2024-10-26_23-03-53](https://github.com/user-attachments/assets/b4f1dd96-add7-45f5-a31b-7e47a803a210)

另外，大大的主题设计的好好看，感谢！

**Comment by rchqi** [comment]
代码为这个，忘用``````了
```
sadsahksa[^1]

[^1]:sdsdfdf
```

**Comment by obscurefreeman** [comment]
收到，过几天我会看看

**Comment by obscurefreeman** [comment]
问题已解决，请下载最新版：https://github.com/obscurefreeman/typora_theme_blackout/releases

- 修复侧边栏大纲可无缩进的问题。
- 调整了`ctrl+p`快速菜单的样式，增加圆角，修改配色，添加鼠标悬停效果，为切尔诺贝利主题添加毛玻璃背景，使其更符合主题。
- 修改了一体化菜单的样式，增加图标，减少不必要的动画。
- 增加脚注留白。

>[!IMPORTANT]
>Typora 快速打开文件时会显示默认高亮第一个文件，可以用键盘右侧的上下键选择文件。

![image](https://github.com/user-attachments/assets/fc74d191-5339-4564-a47b-3a7e23cd3568)
![image](https://github.com/user-attachments/assets/e9803fc7-6f3b-4d66-9c36-2ffe10dbbbc4)
![image](https://github.com/user-attachments/assets/e8d69121-0583-4272-955e-0a622dbe1c47)

**Comment by rchqi** [comment]
感谢，最后问一下大大，脚注的颜色和字体大小可以在哪修改

**Comment by obscurefreeman** [comment]
在`.footnotes`里，我的css里没有规定字体大小，你可以自己找个位置加进去
```
.footnotes {
    opacity: .8;
    font-size: .9rem;
    margin-top: 1em;
    margin-bottom: 1em;
}
```

**Comment by rchqi** [comment]
好的谢谢
