### ISSUE TITLE
Abnormal English font in Preference Setting

### ISSUE THREAD

**Issue by Country-If** [obscurefreeman/typora_theme_blackout#3]
My English font is only abnormal in Preference setting: 
![image](https://github.com/obscurefreeman/typora_theme_blackout/assets/62837275/28df60ca-9979-454f-baa7-b59d9db7a2b4)
How to fix it?

英文字体就只在偏好设置这里出现异常，正文部分没有异常，如何解决？

**Comment by obscurefreeman** [comment]
# 偏好设置栏标题显示不全的问题已解决

## V1.0.4 版本改动

- 给表格增加边框，让它看起来更明显。
- 表格中的链接文字不再显示为白色。
- 给文件选择菜单添加阴影（不明显）。
- 统一`line-height`，让设置栏看起来很正常。（可能会导致一些问题，有待观察）
- 给Blackout主题的h1标题增加了下划线。
- 修复了一些标题的颜色问题。

https://github.com/obscurefreeman/typora_theme_blackout/releases/tag/V1.0.4

如果还有什么使用上的问题欢迎反馈。
