### ISSUE TITLE
表格的边框看不清楚

### ISSUE THREAD

**Issue by BrambleXu** [obscurefreeman/typora_theme_blackout#7]
非常感谢作者创建的主题，用着很舒服。
不过在使用表格的时候，表格和背景的黑色比较近，行之间和列之间的颜色差异也有点小，很难分辨。
希望能改进一下，谢谢！

<img width="1185" alt="image" src="https://github.com/obscurefreeman/typora_theme_blackout/assets/10768193/64ee530e-3653-420d-853c-20426aba973e">

**Comment by obscurefreeman** [comment]
了解，下次更新会改进。

**Comment by obscurefreeman** [comment]
# 表格边框问题已解决

## V1.0.4 版本改动

- 给表格增加边框，让它看起来更明显。
- 表格中的链接文字不再显示为白色。
- 给文件选择菜单添加阴影（不明显）。
- 统一`line-height`，让设置栏看起来很正常。（可能会导致一些问题，有待观察）
- 给Blackout主题的h1标题增加了下划线。
- 修复了一些标题的颜色问题。

https://github.com/obscurefreeman/typora_theme_blackout/releases/tag/V1.0.4

如果还有什么使用上的问题欢迎反馈。
