### ISSUE TITLE
The code syntax becomes a block-level element in Blockquotes

### ISSUE THREAD

**Issue by Zt2tzzt** [obscurefreeman/typora_theme_blackout#8]
The code syntax becomes a block-level element in Blockquotes
In Blackout Theme
![截屏2024-03-10 16 38 22](https://github.com/obscurefreeman/typora_theme_blackout/assets/53403628/4dd6b07c-4a30-4a51-aac6-2a970212a400)
In Github Theme
![截屏2024-03-10 16 41 27](https://github.com/obscurefreeman/typora_theme_blackout/assets/53403628/be996933-feb1-4c30-bf6c-abbe65ea5e90)

**Comment by obscurefreeman** [comment]
了解，下次更新会解决。

**Comment by obscurefreeman** [comment]
### 该问题已被解决
在最新的版本中，引用代码块显示错误的问题已被解决，且标题下划线间隔得到调整。
https://github.com/obscurefreeman/typora_theme_blackout/releases

**Comment by Zt2tzzt** [comment]
Fixed and displayed normally
