### ISSUE TITLE
当链接高亮加粗的时候，链接会看不见

### ISSUE THREAD

**Issue by iamdzk** [obscurefreeman/typora_theme_blackout#9]
加粗高亮的颜色和链接的颜色是一样的，当链接高亮加粗的时候，就会因为颜色颜色一样而完全看不见
![image](https://github.com/obscurefreeman/typora_theme_blackout/assets/58968475/1508b0c2-3f80-4655-b6fd-22ffb14741f5)

**Comment by obscurefreeman** [comment]
### 此问题已在最新版本中解决

图为在最新版本中给链接文本和代码增加高亮的效果。

![image](https://github.com/obscurefreeman/typora_theme_blackout/assets/119153032/7894a3cf-f7f5-44b5-8c18-e8b87ffb18eb)

V1.0.6 版本改动

- 解决了Blackout主题中表格内图片被缩放的问题。
- 修改高亮文字和其他内容的配合，包括链接文本和CODE。
- 修改了代码字体的大小。
- 修改了保存界面样式。
- 修改了按钮样式，给切尔诺贝利主题的部分按钮增加了激活动画。

https://github.com/obscurefreeman/typora_theme_blackout/releases/tag/V1.0.6
